import { sounds as s } from "./sounds";
import { Word } from "./shared_schemas";

export const words = {
  a: { spelling: "a", sounds: [s.a] },
  am: { spelling: "am", sounds: [s.a, s.m] },
  an: { spelling: "an", sounds: [s.a, s.n] },
  and: { spelling: "and", sounds: [s.a, s.n, s.d] },
  ant: { spelling: "ant", sounds: [s.a, s.n, s.t] },
  are: { spelling: "are", sounds: [s.ar], isFunny: true },
  arm: { spelling: "arm", sounds: [s.ar, s.m] },
  as: { spelling: "as", sounds: [s.a, s.z], isFunny: true },
  at: { spelling: "at", sounds: [s.a, s.t] },
  ate: { spelling: "ate", sounds: [s.a_long, s.t] },
  away: { spelling: "away", sounds: [s.a, s.w, s.a_long] },
  back: { spelling: "back", sounds: [s.b, s.a, s.k] },
  bad: { spelling: "bad", sounds: [s.b, s.a, s.d] },
  bag: { spelling: "bag", sounds: [s.b, s.a, s.g] },
  barn: { spelling: "barn", sounds: [s.b, s.ar, s.n] },
  be: { spelling: "be", sounds: [s.b, s.e_long] },
  beagle: { spelling: "beagle", sounds: [s.b, s.e_long, s.g, s.l] },
  bed: { spelling: "bed", sounds: [s.b, s.e, s.d] },
  biff: { spelling: "biff", sounds: [s.b, s.i, s.f] },
  big: { spelling: "big", sounds: [s.b, s.i, s.g] },
  biggest: { spelling: "biggest", sounds: [s.b, s.i, s.g, s.e, s.s, s.t] },
  bill: { spelling: "bill", sounds: [s.b, s.i, s.l] },
  bit: { spelling: "bit", sounds: [s.b, s.i, s.t] },
  bite: { spelling: "bite", sounds: [s.b, s.i_long, s.t] },
  biting: { spelling: "biting", sounds: [s.b, s.i_long, s.t, s.ing] },
  black: { spelling: "black", sounds: [s.b, s.l, s.a, s.k] },
  blap: { spelling: "blap", sounds: [s.b, s.l, s.a, s.p] },
  blam: { spelling: "blam", sounds: [s.b, s.l, s.a, s.m] },
  boo: { spelling: "boo", sounds: [s.b, s.oo] },
  book: { spelling: "book", sounds: [s.b, s.oo, s.k] },
  born: { spelling: "born", sounds: [s.b, s.o_long, s.r, s.n], isFunny: true },
  boy: { spelling: "boy", sounds: [s.b, s.o_long, s.y_long] },
  bring: { spelling: "bring", sounds: [s.b, s.r, s.ing] },
  broke: { spelling: "broke", sounds: [s.b, s.r, s.o_long, s.k] },
  brother: { spelling: "brother", sounds: [s.b, s.r, s.u, s.th, s.er] },
  brush: { spelling: "brush", sounds: [s.b, s.r, s.u, s.sh] },
  brushed: { spelling: "brushed", sounds: [s.b, s.r, s.u, s.sh, s.t] },
  brushing: { spelling: "brushing", sounds: [s.b, s.r, s.u, s.sh, s.ing] },
  bug: { spelling: "bug", sounds: [s.b, s.u, s.g] },
  bugs: { spelling: "bugs", sounds: [s.b, s.u, s.g, s.z] },
  but: { spelling: "but", sounds: [s.b, s.u, s.t] },
  cake: { spelling: "cake", sounds: [s.c, s.a_long, s.k] },
  cakes: { spelling: "cakes", sounds: [s.c, s.a_long, s.k, s.s] },
  came: { spelling: "came", sounds: [s.c, s.a_long, s.m] },
  can: { spelling: "can", sounds: [s.c, s.a, s.n] },
  car: { spelling: "car", sounds: [s.c, s.ar] },
  cars: { spelling: "cars", sounds: [s.c, s.ar, s.z] },
  cat: { spelling: "cat", sounds: [s.c, s.a, s.t] },
  charm: { spelling: "charm", sounds: [s.ch, s.ar, s.m] },
  chick: { spelling: "chick", sounds: [s.ch, s.i, s.k] },
  chicks: { spelling: "chicks", sounds: [s.ch, s.i, s.k, s.s] },
  chop: { spelling: "chop", sounds: [s.ch, s.o, s.p] },
  coat: { spelling: "coat", sounds: [s.c, s.o_long, s.t] },
  coats: { spelling: "coats", sounds: [s.c, s.o_long, s.t, s.s] },
  cold: { spelling: "cold", sounds: [s.c, s.o_long, s.l, s.d] },
  come: { spelling: "come", sounds: [s.c, s.u, s.m], isFunny: true },
  comes: { spelling: "comes", sounds: [s.c, s.u, s.m, s.z], isFunny: true },
  cop: { spelling: "cop", sounds: [s.c, s.o, s.p] },
  cops: { spelling: "cops", sounds: [s.c, s.o, s.p, s.s] },
  corn: { spelling: "corn", sounds: [s.c, s.o_long, s.r, s.n], isFunny: true },
  cow: { spelling: "cow", sounds: [s.c, s.ou] },
  dark: { spelling: "dark", sounds: [s.d, s.ar, s.k] },
  day: { spelling: "day", sounds: [s.d, s.a_long] },
  deal: { spelling: "deal", sounds: [s.d, s.e_long, s.l] },
  deep: { spelling: "deep", sounds: [s.d, s.e_long, s.p] },
  deer: { spelling: "deer", sounds: [s.d, s.e_long, s.r] },
  did: { spelling: "did", sounds: [s.d, s.i, s.d] },
  digging: { spelling: "digging", sounds: [s.d, s.i, s.g, s.ing] },
  dime: { spelling: "dime", sounds: [s.d, s.i_long, s.m] },
  ding: { spelling: "ding", sounds: [s.d, s.ing] },
  dish: { spelling: "dish", sounds: [s.d, s.i, s.sh] },
  dive: { spelling: "dive", sounds: [s.d, s.i_long, s.v] },
  do: { spelling: "do", sounds: [s.d, s.oo], isFunny: true },
  dog: { spelling: "dog", sounds: [s.d, s.o, s.g] },
  dogs: { spelling: "dogs", sounds: [s.d, s.o, s.g, s.z] },
  "don't": { spelling: "don't", sounds: [s.d, s.o_long, s.n, s.t] },
  down: { spelling: "down", sounds: [s.d, s.ou, s.n] },
  duck: { spelling: "duck", sounds: [s.d, s.u, s.k] },
  dug: { spelling: "dug", sounds: [s.d, s.u, s.g] },
  dust: { spelling: "dust", sounds: [s.d, s.u, s.s, s.t] },
  each: { spelling: "each", sounds: [s.e_long, s.ch] },
  eagle: { spelling: "eagle", sounds: [s.e_long, s.g, s.l] },
  "eagle's": { spelling: "eagle's", sounds: [s.e_long, s.g, s.l, s.z] },
  eagles: { spelling: "eagles", sounds: [s.e_long, s.g, s.l, s.z] },
  ear: { spelling: "ear", sounds: [s.e_long, s.r] },
  ears: { spelling: "ears", sounds: [s.e_long, s.r, s.z] },
  eat: { spelling: "eat", sounds: [s.e_long, s.t] },
  eating: { spelling: "eating", sounds: [s.e_long, s.t, s.ing] },
  end: { spelling: "end", sounds: [s.e, s.n, s.d] },
  ever: { spelling: "ever", sounds: [s.e, s.v, s.er] },
  every: { spelling: "every", sounds: [s.e, s.v, s.r, s.e_long] },
  fan: { spelling: "fan", sounds: [s.f, s.a, s.n] },
  far: { spelling: "far", sounds: [s.f, s.ar] },
  farm: { spelling: "farm", sounds: [s.f, s.ar, s.m] },
  farms: { spelling: "farms", sounds: [s.f, s.ar, s.m, s.z] },
  fast: { spelling: "fast", sounds: [s.f, s.a, s.s, s.t] },
  fat: { spelling: "fat", sounds: [s.f, s.a, s.t] },
  feed: { spelling: "feed", sounds: [s.f, s.e_long, s.d] },
  feel: { spelling: "feel", sounds: [s.f, s.e_long, s.l] },
  feet: { spelling: "feet", sounds: [s.f, s.e_long, s.t] },
  fell: { spelling: "fell", sounds: [s.f, s.e, s.l] },
  fill: { spelling: "fill", sounds: [s.f, s.i, s.l] },
  filled: { spelling: "filled", sounds: [s.f, s.i, s.l, s.d] },
  fin: { spelling: "fin", sounds: [s.f, s.i, s.n] },
  find: { spelling: "find", sounds: [s.f, s.i_long, s.n, s.d] },
  fine: { spelling: "fine", sounds: [s.f, s.i_long, s.n] },
  fish: { spelling: "fish", sounds: [s.f, s.i, s.sh] },
  fishing: { spelling: "fishing", sounds: [s.f, s.i, s.sh, s.ing] },
  fit: { spelling: "fit", sounds: [s.f, s.i, s.t] },
  five: { spelling: "five", sounds: [s.f, s.i_long, s.v] },
  fly: { spelling: "fly", sounds: [s.f, s.l, s.y_long] },
  fog: { spelling: "fog", sounds: [s.f, s.o, s.g] },
  fold: { spelling: "fold", sounds: [s.f, s.o_long, s.l, s.d] },
  for: { spelling: "for", sounds: [s.f, s.o_long, s.r], isFunny: true },
  found: { spelling: "found", sounds: [s.f, s.ou, s.n, s.d] },
  from: { spelling: "from", sounds: [s.f, s.r, s.u, s.m], isFunny: true },
  frog: { spelling: "frog", sounds: [s.f, s.r, s.o, s.g] },
  fun: { spelling: "fun", sounds: [s.f, s.u, s.n] },
  game: { spelling: "game", sounds: [s.g, s.a_long, s.m] },
  gas: { spelling: "gas", sounds: [s.g, s.a, s.s] },
  gate: { spelling: "gate", sounds: [s.g, s.a_long, s.t] },
  gates: { spelling: "gates", sounds: [s.g, s.a_long, s.t, s.s] },
  gave: { spelling: "gave", sounds: [s.g, s.a_long, s.v] },
  get: { spelling: "get", sounds: [s.g, s.e, s.t] },
  getting: { spelling: "getting", sounds: [s.g, s.e, s.t, s.ing] },
  girl: { spelling: "girl", sounds: [s.g, s.er, s.l] },
  go: { spelling: "go", sounds: [s.g, s.o_long] },
  goat: { spelling: "goat", sounds: [s.g, s.o_long, s.t] },
  goats: { spelling: "goats", sounds: [s.g, s.o_long, s.t, s.s] },
  going: { spelling: "going", sounds: [s.g, s.o_long, s.ing] },
  gold: { spelling: "gold", sounds: [s.g, s.o_long, s.l, s.d] },
  good: { spelling: "good", sounds: [s.g, s.oo, s.d] },
  got: { spelling: "got", sounds: [s.g, s.o, s.t] },
  grass: { spelling: "grass", sounds: [s.g, s.r, s.a, s.s] },
  green: { spelling: "green", sounds: [s.g, s.r, s.e_long, s.n] },
  gun: { spelling: "gun", sounds: [s.g, s.u, s.n] },
  had: { spelling: "had", sounds: [s.h, s.a, s.d] },
  ham: { spelling: "ham", sounds: [s.h, s.a, s.m] },
  hard: { spelling: "hard", sounds: [s.h, s.ar, s.d] },
  has: { spelling: "has", sounds: [s.h, s.a, s.z], isFunny: true },
  hat: { spelling: "hat", sounds: [s.h, s.a, s.t] },
  hats: { spelling: "hats", sounds: [s.h, s.a, s.t, s.s] },
  hate: { spelling: "hate", sounds: [s.h, s.a_long, s.t] },
  have: { spelling: "have", sounds: [s.h, s.a, s.v], isFunny: true },
  having: { spelling: "having", sounds: [s.h, s.a, s.v, s.ing], isFunny: true },
  he: { spelling: "he", sounds: [s.h, s.e_long] },
  hear: { spelling: "hear", sounds: [s.h, s.e_long, s.r] },
  held: { spelling: "held", sounds: [s.h, s.e, s.l, s.d] },
  her: { spelling: "her", sounds: [s.h, s.er] },
  here: { spelling: "here", sounds: [s.h, s.e_long, s.r] },
  hid: { spelling: "hid", sounds: [s.h, s.i, s.d] },
  hide: { spelling: "hide", sounds: [s.h, s.i_long, s.d] },
  hill: { spelling: "hill", sounds: [s.h, s.i, s.l] },
  him: { spelling: "him", sounds: [s.h, s.i, s.m] },
  his: { spelling: "his", sounds: [s.h, s.i, s.z], isFunny: true },
  hit: { spelling: "hit", sounds: [s.h, s.i, s.t] },
  hits: { spelling: "hits", sounds: [s.h, s.i, s.t, s.s] },
  ho: { spelling: "ho", sounds: [s.h, s.o_long] },
  hold: { spelling: "hold", sounds: [s.h, s.o_long, s.l, s.d] },
  hole: { spelling: "hole", sounds: [s.h, s.o_long, s.l] },
  holes: { spelling: "holes", sounds: [s.h, s.o_long, s.l, s.z] },
  home: { spelling: "home", sounds: [s.h, s.o_long, s.m] },
  hop: { spelling: "hop", sounds: [s.h, s.o, s.p] },
  hope: { spelling: "hope", sounds: [s.h, s.o_long, s.p] },
  horse: { spelling: "horse", sounds: [s.h, s.o_long, s.r, s.s] },
  hot: { spelling: "hot", sounds: [s.h, s.o, s.t] },
  house: { spelling: "house", sounds: [s.h, s.ou, s.s] },
  how: { spelling: "how", sounds: [s.h, s.ou] },
  hug: { spelling: "hug", sounds: [s.h, s.u, s.g] },
  hunt: { spelling: "hunt", sounds: [s.h, s.u, s.n, s.t] },
  hunting: { spelling: "hunting", sounds: [s.h, s.u, s.n, s.t, s.ing] },
  I: { spelling: "I", sounds: [s.I] },
  if: { spelling: "if", sounds: [s.i, s.f] },
  in: { spelling: "in", sounds: [s.i, s.n] },
  inside: { spelling: "inside", sounds: [s.i, s.n, s.s, s.i_long, s.d] },
  into: { spelling: "into", sounds: [s.i, s.n, s.t, s.oo] },
  is: { spelling: "is", sounds: [s.i, s.z], isFunny: true },
  it: { spelling: "it", sounds: [s.i, s.t] },
  jump: { spelling: "jump", sounds: [s.j, s.u, s.m, s.p] },
  jumped: { spelling: "jumped", sounds: [s.j, s.u, s.m, s.p, s.t] },
  jumps: { spelling: "jumps", sounds: [s.j, s.u, s.m, s.p, s.s] },
  just: { spelling: "just", sounds: [s.j, s.u, s.s, s.t] },
  kick: { spelling: "kick", sounds: [s.k, s.i, s.k] },
  kiss: { spelling: "kiss", sounds: [s.k, s.i, s.s] },
  kitten: { spelling: "kitten", sounds: [s.k, s.i, s.t, s.e, s.n] },
  lake: { spelling: "lake", sounds: [s.l, s.a_long, s.k] },
  land: { spelling: "land", sounds: [s.l, s.a, s.n, s.d] },
  last: { spelling: "last", sounds: [s.l, s.a, s.s, s.t] },
  late: { spelling: "late", sounds: [s.l, s.a_long, s.t] },
  leaf: { spelling: "leaf", sounds: [s.l, s.e_long, s.f] },
  leave: { spelling: "leave", sounds: [s.l, s.e_long, s.v] },
  led: { spelling: "led", sounds: [s.l, s.e, s.d] },
  left: { spelling: "left", sounds: [s.l, s.e, s.f, s.t] },
  leg: { spelling: "leg", sounds: [s.l, s.e, s.g] },
  let: { spelling: "let", sounds: [s.l, s.e, s.t] },
  "let's": { spelling: "let's", sounds: [s.l, s.e, s.t, s.s] },
  lick: { spelling: "lick", sounds: [s.l, s.i, s.k] },
  licked: { spelling: "licked", sounds: [s.l, s.i, s.k, s.t] },
  lid: { spelling: "lid", sounds: [s.l, s.i, s.d] },
  like: { spelling: "like", sounds: [s.l, s.i_long, s.k] },
  liked: { spelling: "liked", sounds: [s.l, s.i_long, s.k, s.t] },
  likes: { spelling: "likes", sounds: [s.l, s.i_long, s.k, s.s] },
  line: { spelling: "line", sounds: [s.l, s.i_long, s.n] },
  little: { spelling: "little", sounds: [s.l, s.i, s.t, s.l] },
  live: { spelling: "live", sounds: [s.l, s.i, s.v] },
  lived: { spelling: "lived", sounds: [s.l, s.i, s.v, s.d] },
  lock: { spelling: "lock", sounds: [s.l, s.o, s.k] },
  log: { spelling: "log", sounds: [s.l, s.o, s.g] },
  logs: { spelling: "logs", sounds: [s.l, s.o, s.g, s.z] },
  look: { spelling: "look", sounds: [s.l, s.oo, s.k] },
  looked: { spelling: "looked", sounds: [s.l, s.oo, s.k, s.t] },
  lot: { spelling: "lot", sounds: [s.l, s.o, s.t] },
  lots: { spelling: "lots", sounds: [s.l, s.o, s.t, s.s] },
  loud: { spelling: "loud", sounds: [s.l, s.ou, s.d] },
  love: { spelling: "love", sounds: [s.l, s.u, s.v], isFunny: true },
  luck: { spelling: "luck", sounds: [s.l, s.u, s.k] },
  mad: { spelling: "mad", sounds: [s.m, s.a, s.d] },
  made: { spelling: "made", sounds: [s.m, s.a_long, s.d] },
  make: { spelling: "make", sounds: [s.m, s.a_long, s.k] },
  makes: { spelling: "makes", sounds: [s.m, s.a_long, s.k, s.s] },
  man: { spelling: "man", sounds: [s.m, s.a, s.n] },
  mat: { spelling: "mat", sounds: [s.m, s.a, s.t] },
  me: { spelling: "me", sounds: [s.m, s.e_long] },
  mean: { spelling: "mean", sounds: [s.m, s.e_long, s.n] },
  meat: { spelling: "meat", sounds: [s.m, s.e_long, s.t] },
  meets: { spelling: "meets", sounds: [s.m, s.e_long, s.t, s.s] },
  men: { spelling: "men", sounds: [s.m, s.e, s.n] },
  mile: { spelling: "mile", sounds: [s.m, s.i_long, s.l] },
  mitt: { spelling: "mitt", sounds: [s.m, s.i, s.t] },
  mom: { spelling: "mom", sounds: [s.m, s.o, s.m] },
  moon: { spelling: "moon", sounds: [s.m, s.oo, s.n] },
  mop: { spelling: "mop", sounds: [s.m, s.o, s.p] },
  more: { spelling: "more", sounds: [s.m, s.o_long, s.r] },
  mother: { spelling: "mother", sounds: [s.m, s.u, s.th, s.er] },
  mouse: { spelling: "mouse", sounds: [s.m, s.ou, s.s] },
  mud: { spelling: "mud", sounds: [s.m, s.u, s.d] },
  must: { spelling: "must", sounds: [s.m, s.u, s.s, s.t] },
  my: { spelling: "my", sounds: [s.m, s.y_long] },
  near: { spelling: "near", sounds: [s.n, s.e_long, s.r] },
  need: { spelling: "need", sounds: [s.n, s.e_long, s.d] },
  never: { spelling: "never", sounds: [s.n, s.e, s.v, s.er] },
  nine: { spelling: "nine", sounds: [s.n, s.i_long, s.n] },
  no: { spelling: "no", sounds: [s.n, s.o_long] },
  nod: { spelling: "nod", sounds: [s.n, s.o, s.d] },
  nose: { spelling: "nose", sounds: [s.n, s.o_long, s.z] },
  noses: { spelling: "noses", sounds: [s.n, s.o_long, s.z, s.e, s.z] },
  not: { spelling: "not", sounds: [s.n, s.o, s.t] },
  note: { spelling: "note", sounds: [s.n, s.o_long, s.t] },
  notes: { spelling: "notes", sounds: [s.n, s.o_long, s.t, s.s] },
  now: { spelling: "now", sounds: [s.n, s.ou] },
  nut: { spelling: "nut", sounds: [s.n, s.u, s.t] },
  of: { spelling: "of", sounds: [s.u, s.v], isFunny: true },
  old: { spelling: "old", sounds: [s.o_long, s.l, s.d] },
  on: { spelling: "on", sounds: [s.o, s.n] },
  or: { spelling: "or", sounds: [s.o_long, s.r] },
  other: { spelling: "other", sounds: [s.u, s.th, s.er] },
  our: { spelling: "our", sounds: [s.ou, s.r] },
  out: { spelling: "out", sounds: [s.ou, s.t] },
  outside: { spelling: "outside", sounds: [s.ou, s.t, s.s, s.i_long, s.d] },
  over: { spelling: "over", sounds: [s.o_long, s.v, s.er] },
  pail: { spelling: "pail", sounds: [s.p, s.a_long, s.l] },
  pain: { spelling: "pain", sounds: [s.p, s.a_long, s.n] },
  paint: { spelling: "paint", sounds: [s.p, s.a_long, s.n, s.t] },
  park: { spelling: "park", sounds: [s.p, s.ar, s.k] },
  part: { spelling: "part", sounds: [s.p, s.ar, s.t] },
  pet: { spelling: "pet", sounds: [s.p, s.e, s.t] },
  pick: { spelling: "pick", sounds: [s.p, s.i, s.k] },
  picked: { spelling: "picked", sounds: [s.p, s.i, s.k, s.t] },
  pig: { spelling: "pig", sounds: [s.p, s.i, s.g] },
  play: { spelling: "play", sounds: [s.p, s.l, s.a_long] },
  pool: { spelling: "pool", sounds: [s.p, s.oo, s.l] },
  pot: { spelling: "pot", sounds: [s.p, s.o, s.t] },
  pots: { spelling: "pots", sounds: [s.p, s.o, s.t, s.s] },
  proud: { spelling: "proud", sounds: [s.p, s.r, s.ou, s.d] },
  quick: { spelling: "quick", sounds: [s.qu, s.i, s.k] },
  quit: { spelling: "quit", sounds: [s.qu, s.i, s.t] },
  quitting: { spelling: "quitting", sounds: [s.qu, s.i, s.t, s.ing] },
  rack: { spelling: "rack", sounds: [s.r, s.a, s.k] },
  rag: { spelling: "rag", sounds: [s.r, s.a, s.g] },
  rain: { spelling: "rain", sounds: [s.r, s.a_long, s.n] },
  ram: { spelling: "ram", sounds: [s.r, s.a, s.m] },
  ran: { spelling: "ran", sounds: [s.r, s.a, s.n] },
  rat: { spelling: "rat", sounds: [s.r, s.a, s.t] },
  read: { spelling: "read", sounds: [s.r, s.e_long, s.d] },
  red: { spelling: "red", sounds: [s.r, s.e, s.d] },
  rich: { spelling: "rich", sounds: [s.r, s.i, s.ch] },
  rid: { spelling: "rid", sounds: [s.r, s.i, s.d] },
  road: { spelling: "road", sounds: [s.r, s.o_long, s.d] },
  rock: { spelling: "rock", sounds: [s.r, s.o, s.k] },
  rocks: { spelling: "rocks", sounds: [s.r, s.o, s.k, s.s] },
  rod: { spelling: "rod", sounds: [s.r, s.o, s.d] },
  room: { spelling: "room", sounds: [s.r, s.oo, s.m] },
  rub: { spelling: "rub", sounds: [s.r, s.u, s.b] },
  ruck: { spelling: "ruck", sounds: [s.r, s.u, s.k] },
  rug: { spelling: "rug", sounds: [s.r, s.u, s.g] },
  run: { spelling: "run", sounds: [s.r, s.u, s.n] },
  sad: { spelling: "sad", sounds: [s.s, s.a, s.d] },
  said: { spelling: "said", sounds: [s.s, s.e, s.d], isFunny: true },
  same: { spelling: "same", sounds: [s.s, s.a_long, s.m] },
  sam: { spelling: "sam", sounds: [s.s, s.a, s.m] },
  sand: { spelling: "sand", sounds: [s.s, s.a, s.n, s.d] },
  sat: { spelling: "sat", sounds: [s.s, s.a, s.t] },
  save: { spelling: "save", sounds: [s.s, s.a_long, s.v] },
  saved: { spelling: "saved", sounds: [s.s, s.a_long, s.v, s.d] },
  say: { spelling: "say", sounds: [s.s, s.a_long] },
  seat: { spelling: "seat", sounds: [s.s, s.e_long, s.t] },
  see: { spelling: "see", sounds: [s.s, s.e_long] },
  seed: { spelling: "seed", sounds: [s.s, s.e_long, s.d] },
  seem: { spelling: "seem", sounds: [s.s, s.e_long, s.m] },
  seen: { spelling: "seen", sounds: [s.s, s.e_long, s.n] },
  shack: { spelling: "shack", sounds: [s.sh, s.a, s.k] },
  she: { spelling: "she", sounds: [s.sh, s.e_long] },
  sheep: { spelling: "sheep", sounds: [s.sh, s.e_long, s.p] },
  shine: { spelling: "shine", sounds: [s.sh, s.i_long, s.n] },
  ship: { spelling: "ship", sounds: [s.sh, s.i, s.p] },
  shop: { spelling: "shop", sounds: [s.sh, s.o, s.p] },
  shore: { spelling: "shore", sounds: [s.sh, s.o_long, s.r] },
  shot: { spelling: "shot", sounds: [s.sh, s.o, s.t] },
  shouted: { spelling: "shouted", sounds: [s.sh, s.ou, s.t, s.e, s.d] },
  sick: { spelling: "sick", sounds: [s.s, s.i, s.k] },
  side: { spelling: "side", sounds: [s.s, s.i_long, s.d] },
  sin: { spelling: "sin", sounds: [s.s, s.i, s.n] },
  sing: { spelling: "sing", sounds: [s.s, s.ing] },
  singing: { spelling: "singing", sounds: [s.s, s.ing, s.ing] },
  sit: { spelling: "sit", sounds: [s.s, s.i, s.t] },
  sitting: { spelling: "sitting", sounds: [s.s, s.i, s.t, s.ing] },
  sleep: { spelling: "sleep", sounds: [s.s, s.l, s.e_long, s.p] },
  sleeping: { spelling: "sleeping", sounds: [s.s, s.l, s.e_long, s.p, s.ing] },
  smell: { spelling: "smell", sounds: [s.s, s.m, s.e, s.l] },
  smile: { spelling: "smile", sounds: [s.s, s.m, s.i_long, s.l] },
  smiled: { spelling: "smiled", sounds: [s.s, s.m, s.i_long, s.l, s.d] },
  so: { spelling: "so", sounds: [s.s, s.o_long] },
  sock: { spelling: "sock", sounds: [s.s, s.o, s.k] },
  socks: { spelling: "socks", sounds: [s.s, s.o, s.k, s.s] },
  sold: { spelling: "sold", sounds: [s.s, s.o_long, s.l, s.d] },
  some: { spelling: "some", sounds: [s.s, s.u, s.m], isFunny: true },
  something: { spelling: "something", sounds: [s.s, s.u, s.m, s.th, s.ing] },
  soon: { spelling: "soon", sounds: [s.s, s.oo, s.n] },
  sore: { spelling: "sore", sounds: [s.s, s.o_long, s.r] },
  sound: { spelling: "sound", sounds: [s.s, s.ou, s.n, s.d] },
  sounds: { spelling: "sounds", sounds: [s.s, s.ou, s.n, s.d, s.z] },
  spots: { spelling: "spots", sounds: [s.s, s.p, s.o, s.t, s.s] },
  spring: { spelling: "spring", sounds: [s.s, s.p, s.r, s.ing] },
  start: { spelling: "start", sounds: [s.s, s.t, s.ar, s.t] },
  started: { spelling: "started", sounds: [s.s, s.t, s.ar, s.t, s.e, s.d] },
  stay: { spelling: "stay", sounds: [s.s, s.t, s.a_long] },
  stop: { spelling: "stop", sounds: [s.s, s.t, s.o, s.p] },
  stopped: { spelling: "stopped", sounds: [s.s, s.t, s.o, s.p, s.t] },
  stopping: { spelling: "stopping", sounds: [s.s, s.t, s.o, s.p, s.ing] },
  store: { spelling: "store", sounds: [s.s, s.t, s.o_long, s.r] },
  story: { spelling: "story", sounds: [s.s, s.t, s.o_long, s.r, s.y_long] },
  sun: { spelling: "sun", sounds: [s.s, s.u, s.n] },
  swam: { spelling: "swam", sounds: [s.s, s.w, s.a, s.m] },
  swim: { spelling: "swim", sounds: [s.s, s.w, s.i, s.m] },
  swimming: { spelling: "swimming", sounds: [s.s, s.w, s.i, s.m, s.ing] },
  sack: { spelling: "sack", sounds: [s.s, s.a, s.k] },
  sacks: { spelling: "sacks", sounds: [s.s, s.a, s.k, s.s] },
  tail: { spelling: "tail", sounds: [s.t, s.a_long, s.l] },
  take: { spelling: "take", sounds: [s.t, s.a_long, s.k] },
  talk: { spelling: "talk", sounds: [s.t, s.o, s.k], isFunny: true },
  talked: { spelling: "talked", sounds: [s.t, s.o, s.k, s.t], isFunny: true },
  talking: { spelling: "talking", sounds: [s.t, s.o, s.k, s.ing], isFunny: true },
  talks: { spelling: "talks", sounds: [s.t, s.o, s.k, s.s], isFunny: true },
  tame: { spelling: "tame", sounds: [s.t, s.a_long, s.m] },
  tar: { spelling: "tar", sounds: [s.t, s.ar] },
  teach: { spelling: "teach", sounds: [s.t, s.e_long, s.ch] },
  teaching: { spelling: "teaching", sounds: [s.t, s.e_long, s.ch, s.ing] },
  teeth: { spelling: "teeth", sounds: [s.t, s.e_long, s.th] },
  tell: { spelling: "tell", sounds: [s.t, s.e, s.l] },
  ten: { spelling: "ten", sounds: [s.t, s.e, s.n] },
  thank: { spelling: "thank", sounds: [s.th, s.a, s.n, s.k] },
  that: { spelling: "that", sounds: [s.th, s.a, s.t] },
  the: { spelling: "the", sounds: [s.th, s.u], isFunny: true },
  them: { spelling: "them", sounds: [s.th, s.e, s.m] },
  then: { spelling: "then", sounds: [s.th, s.e, s.n] },
  there: { spelling: "there", sounds: [s.th, s.e_long, s.r] },
  these: { spelling: "these", sounds: [s.th, s.e_long, s.z] },
  they: { spelling: "they", sounds: [s.th, s.a_long], isFunny: true },
  thing: { spelling: "thing", sounds: [s.th, s.ing] },
  things: { spelling: "things", sounds: [s.th, s.ing, s.z] },
  this: { spelling: "this", sounds: [s.th, s.i, s.s] },
  those: { spelling: "those", sounds: [s.th, s.o_long, s.z] },
  tiger: { spelling: "tiger", sounds: [s.t, s.i_long, s.g, s.er] },
  tigers: { spelling: "tigers", sounds: [s.t, s.i_long, s.g, s.er, s.z] },
  time: { spelling: "time", sounds: [s.t, s.i_long, s.m] },
  to: { spelling: "to", sounds: [s.t, s.oo], isFunny: true },
  told: { spelling: "told", sounds: [s.t, s.o_long, s.l, s.d] },
  too: { spelling: "too", sounds: [s.t, s.oo] },
  took: { spelling: "took", sounds: [s.t, s.oo, s.k] },
  top: { spelling: "top", sounds: [s.t, s.o, s.p] },
  tops: { spelling: "tops", sounds: [s.t, s.o, s.p, s.s] },
  tore: { spelling: "tore", sounds: [s.t, s.o_long, s.r] },
  torn: { spelling: "torn", sounds: [s.t, s.o_long, s.r, s.n] },
  town: { spelling: "town", sounds: [s.t, s.ou, s.n] },
  toy: { spelling: "toy", sounds: [s.t, s.o_long, s.y_long], isFunny: true },
  tree: { spelling: "tree", sounds: [s.t, s.r, s.e_long] },
  trees: { spelling: "trees", sounds: [s.t, s.r, s.e_long, s.z] },
  tub: { spelling: "tub", sounds: [s.t, s.u, s.b] },
  under: { spelling: "under", sounds: [s.u, s.n, s.d, s.er] },
  up: { spelling: "up", sounds: [s.u, s.p] },
  us: { spelling: "us", sounds: [s.u, s.s] },
  very: { spelling: "very", sounds: [s.v, s.e, s.r, s.e_long] },
  walk: { spelling: "walk", sounds: [s.w, s.o, s.k], isFunny: true },
  walked: { spelling: "walked", sounds: [s.w, s.o, s.k, s.t], isFunny: true },
  walking: { spelling: "walking", sounds: [s.w, s.o, s.k, s.ing], isFunny: true },
  want: { spelling: "want", sounds: [s.w, s.o, s.n, s.t], isFunny: true },
  was: { spelling: "was", sounds: [s.w, s.u, s.z], isFunny: true },
  waves: { spelling: "waves", sounds: [s.w, s.a_long, s.v, s.z] },
  way: { spelling: "way", sounds: [s.w, s.a_long] },
  we: { spelling: "we", sounds: [s.w, s.e_long] },
  well: { spelling: "well", sounds: [s.w, s.e, s.l] },
  went: { spelling: "went", sounds: [s.w, s.e, s.n, s.t] },
  were: { spelling: "were", sounds: [s.w, s.er], isFunny: true },
  wet: { spelling: "wet", sounds: [s.w, s.e, s.t] },
  when: { spelling: "when", sounds: [s.wh, s.e, s.n] },
  where: { spelling: "where", sounds: [s.wh, s.e_long, s.r] },
  white: { spelling: "white", sounds: [s.wh, s.i_long, s.t] },
  will: { spelling: "will", sounds: [s.w, s.i, s.l] },
  win: { spelling: "win", sounds: [s.w, s.i, s.n] },
  wish: { spelling: "wish", sounds: [s.w, s.i, s.sh] },
  with: { spelling: "with", sounds: [s.w, s.i, s.th] },
  wow: { spelling: "wow", sounds: [s.w, s.ou] },
  yard: { spelling: "yard", sounds: [s.y, s.ar, s.d] },
  year: { spelling: "year", sounds: [s.y, s.e_long, s.r] },
  yell: { spelling: "yell", sounds: [s.y, s.e, s.l] },
  yelled: { spelling: "yelled", sounds: [s.y, s.e, s.l, s.d] },
  yelling: { spelling: "yelling", sounds: [s.y, s.e, s.l, s.ing] },
  yes: { spelling: "yes", sounds: [s.y, s.e, s.s] },
  you: { spelling: "you", sounds: [s.y, s.oo], isFunny: true },
  zoom: { spelling: "zoom", sounds: [s.z, s.oo, s.m] },
} satisfies Record<string, Word>;
